# Generated by Django 5.2.8 on 2026-02-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='userslogin',
        ),
    ]
